### ISSUE TITLE
Crashes on first start of session

### ISSUE THREAD

**Issue by bet** [CypherpunkArmory/UserLAnd#140]
Seems to crash silently either with ubuntu or debian. I switched to a network (different wifi hotspot) that doesn't try to MITM https and either works now. If I may suggest an improvement, showing a message, even a "toast", on the way out might be helpful. P.S. this is with the release that I just got as an update from Google Play

**Comment by lapsio** [comment]
I'm gonna get into this thread - after recent update Userland started downloading some files. Due to turbulent connection it didn't finish. Crashed in the middle of downloading. Now app crashes every time I try to open it. Is there any way to reinstall app without loosing current system? I had plenty of important data here :/

**Comment by corbinlc** [comment]
Does long pressing the session and telling it to update help fix this?

**Comment by lapsio** [comment]
It crashes literally at app launch. It doesn't even open UI. Crashes right
after clicking UserLAnd icon in Android launcher

**Comment by MatthewTighe** [comment]
@lapsio Just to clarify, you previously set up a filesystem and run a session on it?

**Comment by lapsio** [comment]
Yeah that's actually something I wanted to ask - I'm using UserLAnd since
ore-release and I had pretty advanced root setup with many custom config
files like screen, pulseaudio and python based sftp server... Is there any
way I can recover files from my root?

It was root used before without any problem. Today when I attempted to
launch it UserLAnd started downloading some files (13 of them iirc) at 5th
or 6th file app crashed. And now I can't launch app at all.

UserLAnd app has crash syndrome when it's downloading / processing
something and I move it to background. It happened many times before. I
just think it never made app unusable like now.

**Comment by lapsio** [comment]
by root I referred to filesystem

**Comment by corbinlc** [comment]
@lapsio .  Issues related to moving the app to the background "should" be solved.  Those were particularly solved.  We are thinking of some escape cases where a download might have failed during an update.  Can you get a logcat?  I don't see a ANR or Crash report from a device in the last little bit.  
If you don't know how to get a logcat, we can help guide you through that process.
There is not a clear way to recover right now, so my hope is we would be able to quickly provide a new version that handles whatever bad situation you are in more gracefully.

**Comment by lapsio** [comment]
Sure. I actually sent this mail as crash report and ticked "Send system
log" so I thought it'd include some crash logs.

Anyways I can provide you with more debug info tomorrow, just tell me what
to do

I'm using Linux OpenSUSE on my PCs and my phone is Asus ZS570KL. Not
rooted. Android 8.0.0, security update 5 june 2018.

**Comment by corbinlc** [comment]
@bet are you saying for you, your issue was solved once you switch networks?   I am specifically asking about this sentence "I switched to a network (different wifi hotspot) that doesn't try to MITM https and either works now"

**Comment by lapsio** [comment]
wrong thread xd

**Comment by bet** [comment]
Yes. When I first tried the update from Google Play it crashed as soon as I tried to open a session, until I switched from a work wifi to a public one, so I think it was failures in the initial download.

**Comment by lapsio** [comment]
Didn't help in my case. I switched to 3g and app still crashes.

**Comment by corbinlc** [comment]
I think we have two different issues.  1) if there is internet connectivity, but it cannot reach our files the app might crash and 2) if the downloads start but fail somewhere it the process the app might crash.

**Comment by corbinlc** [comment]
@MatthewTighe , @luongthomas and me will get this fixed up.  We are looking forward to seeing your logcat to help confirm our suspicions

**Comment by lapsio** [comment]
though I'd like to repeat that app crashes instantly. I can't even choose
sessions or anything. It doesn't even manage to show UI, only screen gets
grey for split of second (UserLAnd app background color) and then
immediately crashes

**Comment by corbinlc** [comment]
understood

**Comment by lapsio** [comment]
How do I make logcat

**Comment by corbinlc** [comment]
There are multiple apps that say they can read the logcat.  Please go to the play store and see if there is one that works with your device and android version (literally seach for logcat).  If that doesn't work it can be done via Android Studio or just adb.

**Comment by corbinlc** [comment]
Researching which ones work well for us.  Regardless of which app you use, you need to launch them before creating the situation.

**Comment by lapsio** [comment]
All those apps require either root or remote debugging to be turned on so
I'll just use adb. I'll send log tomorrow because it's quite late, thank
you for assistance :)

**Comment by corbinlc** [comment]
Yes.  I just came to the same conclusion that even the ones that say they can run without root still require extra work.  Once you have adb install it should just be `adb logcat`

**Comment by lapsio** [comment]
Here are multiple logcats. First crashed bilion of times but may be big,
second I tried to activate logcat, crash and stop logcat as fast as I can
to avoid spam and third is the same just app is launched using conventional
launcher instead of MeteorSwipe shortscut to minimize log even more. I hope
it helps.

If you could tell what's fully qualified name of your app (I mean this
"com.something.something") then I could maybe run logcat only for your app.

**Comment by lapsio** [comment]
Link: https://cloud.traffordit.pl/public/5d3449--en

It'll expire in 2 days so please download files if you're gonna need them
later.

**Comment by corbinlc** [comment]
We think that #149 will fix these issue.  You should see a version 0.2.4 in the Play Store in a couple of hours.  This should allow @lapsio to at least get in the app.  I am not 100% certain you won't hit another issue since you were left it a bad state, but it should get you past the first issue that was causing you to crash according to your logcat.  Tell us how it goes and if it is still not working, please provide us with how it is breaking now and please provide a logcat.

**Comment by corbinlc** [comment]
@lapsio any update?

**Comment by lapsio** [comment]
https://cloud.traffordit.pl/public/5d3449--en

logcat6

Still crashes at startup and still UI is not displayed.

**Comment by corbinlc** [comment]
It is the same crash.  Can you go to settings->apps->UserLAnd and confirm what version number it shows?  If you have the latest we will have to see why the exception is not being handled as planned.

**Comment by corbinlc** [comment]
It is the same crash.  Can you go to settings->apps->UserLAnd and confirm what version number it shows?  If you have the latest we will have to see why the exception is not being handled as planned.

**Comment by lapsio** [comment]
0.2.4. I rebooted phone twice and force stopped app before running logcat
to me sure that update is active.

**Comment by corbinlc** [comment]
@lapsio There is a new update coming that should do better for your specific crash.  It is 0.2.5.  Once you see it available, please try it and tell us how it goes.

**Comment by lapsio** [comment]
Yeah, fixed. System booted up properly.

**Comment by linux0torvald** [comment]
I'm having issue with sudo,when I try to install any package,it says dpkg require superuser previlege 😢😢
